### PR TITLE
pokemon: parse dex number from template id

### PR DESCRIPTION
**Pull request by dominicbarnes**
This PR parses out the "dex number" (eg: Bulbasaur: 1, Mew: 151) from the template ID (eg: "V0001_POKEMON_BULBASAUR", "V0151_POKEMON_MEW").

I'm starting to use this JSON in another project, and the dex number is really good for sorting.

### CODE REVIEW

**Comment by dominicbarnes** [comment]
This is my first time using TypeScript, so apologies if I've done something incorrectly.

**Comment by proegssilb** [comment]
Please update the tests with at least one general-case test (ie, all dex numbers are greater than 0 and less than ____), and at least one pokemon-specific test from each of Gen 1 and Gen 2 (ie, Mr. Mime has a dex number of 122).

I'll let @BrunnerLivio comment on code quality itself.

**Comment by dominicbarnes** [comment]
@proegssilb test cases added!

**Comment by BrunnerLivio** [comment]
I think the code is alright, thanks alot!
Ready to merge from my point of view.

Edit:
Saw something; can you move the `extractDexNumber`-function from `pokemon.mapper.ts` to a new file called `components/pokemon/shared/dex-number-parser.component.ts` and implement the `Component`-interface like in `components/avatar-customization/shared/category-parser.component.ts` ?

Then call the moved function in PokemonMapper.Map()

And also, please use JSDOC for method and classes. So instead of 

```JavaScript
// parse the dex number out of the templateId
// (eg: "V0151_POKEMON_MEW" => 151)
```

```
/*
 * Parses the dex number out of the templateId
 * @param input {String} The templateId string of a pokemon
 * @returns {Number} The dex number of the given templateId-string
 * @example
 * new DexNumberParser().Process('V0151_POKEMON_MEW'); // 151
 */
```

**Comment by dominicbarnes** [comment]
@BrunnerLivio done!

**Pull request merged**
