### PR TITLE
Fix typescript regex attribute error

### PR DESCRIPTION
**Pull request by BrunnerLivio**
Fix issue #28

Really strange behaviour. I don't want to do fingerpointing, but to me it seems like a TypeScript error. Not 100% sure though. Will investigate more later where the problem actually was. 

Anyway it works now as expected.

### CODE REVIEW

**Comment by proegssilb** [comment]
I see that you changed the parser files, but why is there no test for how many items are there? That way, we could watch changes to TypeScript/NodeJS regexes, and periodically see if they've fixed our use case.

There is a performance hit with this change, but it's likely not relevant to our circumstances.

**Comment by BrunnerLivio** [comment]
@proegssilb  
Yes thats a great idea. Thought do you have an idea how we get the moves / avatarcostumization lengthwhich will be tested? What I mean by that; currently the array of `output/move.json` has 177 items. Can we be sure that this is currently the actual amount of moves in pogo, or does our code has another bug? 

I think we should not bother about that performance issue.

**Comment by proegssilb** [comment]
http://www.serebii.net/pokemongo/moves.shtml lists 58 fast moves and 118 special moves, totaling 176. That's close enough for a possible math error, since Serebii's tables don't have proper thead tags. Feel free to double-check my math, though.

**Comment by BrunnerLivio** [comment]
@proegssilb I count 176 using jQuery counting the "<tr>"-Elements of those tables. Kinda hard to find out who's wrong :/

**Comment by proegssilb** [comment]
I tried to use python to do a diff against the moves in the JSON and the moves on Serebii, but the results were extremely poor. Manually searched for all moves reported in the issue, and they're present, possibly with the suffix "Fast". Merging.

**Comment by BrunnerLivio** [comment]
I also saw that Serebii removed the "Fast" suffix. I think we should do that too. I create an issue for that.

**Pull request merged**
