### PR TITLE
Added internalId number to move.json

### PR DESCRIPTION
**Pull request by vfcp**
move.json was lacking the internal id of the move.

Added similar to what was implemented for pokemon dex number.

### CODE REVIEW

**Comment by proegssilb** [comment]
Is "dex" really the best name for the move id number? Is "DexParser" the best name possible for the new component you added?

Could you describe why the new field is beneficial to you? How are you using it/how do you plan to use it?

**Comment by vfcp** [comment]
The reason I need the internal id is because pogo APIs and webhooks from RM expose only the move numerical id, not the move name.

I agree that dex is not the best name, as it relates more to Pokedex but it can also be seen as a short for index which in that case makes some sense. Everything else, I've just copy what was done for dex in Pokemon class, so same component and style would be reused. Open to suggestions (numericalId, internalId, apiId...)

**Comment by proegssilb** [comment]
I'm leaning towards `PogoIntId`, but my usual preferences tend to be sub-optimal according to @BrunnerLivio , so maybe they should chime in.

**Comment by BrunnerLivio** [comment]
Thanks for the pull request!

My 2 cents;
As far as I know, this move-Id we're talking about, is a Pogo specific-thingy. I compared it with [this list](https://bulbapedia.bulbagarden.net/wiki/List_of_moves) and the ids don't match up. So if my assumption is true, `dex` would be a bad name in my opinion.

@proegssilb I'm not sure what you mean with "Int" in `PogoIntId`? "Integer" or "Internal"? But I agree we should use something in this direction. I would actually go with `internalId`. Do you see any inconvenience with that?

**Comment by proegssilb** [comment]
I meant "Integer", but the confusion is totally valid. `internalId` is fine by me.

@BrunnerLivio , that list is likely numbered based on the canonical pokemon video games (Red, Blue, Gold, Silver, ...). [This link](https://bulbapedia.bulbagarden.net/wiki/List_of_moves_in_Pok%C3%A9mon_GO) is more likely to have the numbers right, but it still reads odd to me.

**Comment by BrunnerLivio** [comment]
@vfcp There you have it. Change `dex` to `internalId` (in Model, Component, ...) and the PR should be ready to merge!

**Comment by vfcp** [comment]
`dex `renamed to `internalId` as suggested. Also added a test to move output to validate internalId is defined.

**Pull request merged**
